name: Tests
on:
  push:
  pull_request:
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache tox env
        uses: actions/cache@v4
        with:
          path: .tox
          key: tox-cache-${{ runner.os }}-${{ hashFiles('requirements-tests.txt') }}-test
      - name: Install tox
        run: pip install tox
      - name: Install test data
        run: git clone -b tests --single-branch https://github.com/ISA-tools/ISAdatasets tests/data
      - name: Run tox
        run: tox
